const users = [
  {
    id: 1,
    name: "Valry Jouanny",
    age: 48,
  },
  {
    id: 2,
    name: "Nert Whear",
    age: 60,
  },
  {
    id: 3,
    name: "Uri Kennan",
    age: 24,
  },
  {
    id: 4,
    name: "Analiese Emblow",
    age: 50,
  },
  {
    id: 5,
    name: "Juliette Montilla",
    age: 39,
  },
  {
    id: 6,
    name: "Stan Ranfield",
    age: 40,
  },
  {
    id: 7,
    name: "Brockie Benallack",
    age: 22,
  },
  {
    id: 8,
    name: "Bernarr Evers",
    age: 25,
  },
  {
    id: 9,
    name: "Pat Durtnel",
    age: 36,
  },
  {
    id: 10,
    name: "Caralie Penhallurick",
    age: 25,
  },
  {
    id: 11,
    name: "Eloisa Dewfall",
    age: 36,
  },
  {
    id: 12,
    name: "Mireille O'Doherty",
    age: 58,
  },
  {
    id: 13,
    name: "Willdon Wimlet",
    age: 37,
  },
  {
    id: 14,
    name: "Justinian Huller",
    age: 46,
  },
  {
    id: 15,
    name: "Bary MacGarrity",
    age: 22,
  },
  {
    id: 16,
    name: "Chadwick Kneeland",
    age: 24,
  },
  {
    id: 17,
    name: "Fleur Mellanby",
    age: 54,
  },
  {
    id: 18,
    name: "Thornie Goldsack",
    age: 42,
  },
  {
    id: 19,
    name: "Adoree Sclanders",
    age: 22,
  },
  {
    id: 20,
    name: "Edsel Hambleton",
    age: 42,
  },
  {
    id: 21,
    name: "Bertram Perritt",
    age: 40,
  },
  {
    id: 22,
    name: "Annora Bicknell",
    age: 46,
  },
  {
    id: 23,
    name: "Elsey Luke",
    age: 20,
  },
  {
    id: 24,
    name: "Kingsley Privett",
    age: 28,
  },
  {
    id: 25,
    name: "Nonah Branton",
    age: 51,
  },
  {
    id: 26,
    name: "Yolande Felgate",
    age: 55,
  },
  {
    id: 27,
    name: "Smitty Cowden",
    age: 40,
  },
  {
    id: 28,
    name: "Noell Mewes",
    age: 25,
  },
  {
    id: 29,
    name: "Sapphire Johnke",
    age: 47,
  },
  {
    id: 30,
    name: "Ronda Harflete",
    age: 18,
  },
  {
    id: 31,
    name: "Linnie Adanez",
    age: 38,
  },
  {
    id: 32,
    name: "Burgess Kinningley",
    age: 42,
  },
  {
    id: 33,
    name: "Emmalee Phin",
    age: 27,
  },
  {
    id: 34,
    name: "Janelle Hasser",
    age: 52,
  },
  {
    id: 35,
    name: "Star Grabert",
    age: 30,
  },
  {
    id: 36,
    name: "Elyssa Halfhead",
    age: 28,
  },
  {
    id: 37,
    name: "Kiah Petrulis",
    age: 48,
  },
  {
    id: 38,
    name: "Madalena Shuard",
    age: 60,
  },
  {
    id: 39,
    name: "Alvira Bozier",
    age: 52,
  },
  {
    id: 40,
    name: "Jed Trenbey",
    age: 41,
  },
];

const posts = [
  {
    id: 1,
    text: "Curabitur in libero ut massa volutpat convallis.",
    author: 4,
  },
  {
    id: 2,
    text: "Duis consequat dui nec nisi volutpat eleifend.",
    author: 10,
  },
  {
    id: 3,
    text: "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",
    author: 29,
  },
  {
    id: 4,
    text: "In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.",
    author: 33,
  },
  {
    id: 5,
    text: "Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.",
    author: 4,
  },
  {
    id: 6,
    text: "Proin interdum mauris non ligula pellentesque ultrices.",
    author: 2,
  },
  {
    id: 7,
    text: "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.",
    author: 8,
  },
  {
    id: 8,
    text: "Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.",
    author: 38,
  },
  {
    id: 9,
    text: "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.",
    author: 39,
  },
  {
    id: 10,
    text: "Mauris lacinia sapien quis libero.",
    author: 29,
  },
  {
    id: 11,
    text: "Vestibulum rutrum rutrum neque.",
    author: 27,
  },
  {
    id: 12,
    text: "Morbi vel lectus in quam fringilla rhoncus.",
    author: 30,
  },
  {
    id: 13,
    text: "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.",
    author: 5,
  },
  {
    id: 14,
    text: "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    author: 15,
  },
  {
    id: 15,
    text: "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.",
    author: 23,
  },
  {
    id: 16,
    text: "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.",
    author: 17,
  },
  {
    id: 17,
    text: "Proin eu mi.",
    author: 13,
  },
  {
    id: 18,
    text: "Aliquam erat volutpat. In congue.",
    author: 26,
  },
  {
    id: 19,
    text: "Morbi non lectus.",
    author: 35,
  },
  {
    id: 20,
    text: "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
    author: 17,
  },
  {
    id: 21,
    text: "In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.",
    author: 36,
  },
  {
    id: 22,
    text: "Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.",
    author: 35,
  },
  {
    id: 23,
    text: "Sed vel enim sit amet nunc viverra dapibus.",
    author: 23,
  },
  {
    id: 24,
    text: "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",
    author: 29,
  },
  {
    id: 25,
    text: "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.",
    author: 40,
  },
  {
    id: 26,
    text: "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.",
    author: 31,
  },
  {
    id: 27,
    text: "Nunc rhoncus dui vel sem.",
    author: 40,
  },
  {
    id: 28,
    text: "Ut at dolor quis odio consequat varius. Integer ac leo.",
    author: 15,
  },
  {
    id: 29,
    text: "Integer ac leo. Pellentesque ultrices mattis odio.",
    author: 8,
  },
  {
    id: 30,
    text: "In hac habitasse platea dictumst.",
    author: 27,
  },
  {
    id: 31,
    text: "Praesent blandit. Nam nulla.",
    author: 25,
  },
  {
    id: 32,
    text: "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.",
    author: 31,
  },
  {
    id: 33,
    text: "Aliquam sit amet diam in magna bibendum imperdiet.",
    author: 22,
  },
  {
    id: 34,
    text: "Integer a nibh.",
    author: 25,
  },
  {
    id: 35,
    text: "Maecenas rhoncus aliquam lacus.",
    author: 28,
  },
  {
    id: 36,
    text: "Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
    author: 21,
  },
  {
    id: 37,
    text: "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.",
    author: 4,
  },
  {
    id: 38,
    text: "Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.",
    author: 34,
  },
  {
    id: 39,
    text: "Nulla ut erat id mauris vulputate elementum.",
    author: 32,
  },
  {
    id: 40,
    text: "Nunc rhoncus dui vel sem.",
    author: 8,
  },
  {
    id: 41,
    text: "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",
    author: 5,
  },
  {
    id: 42,
    text: "Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
    author: 15,
  },
  {
    id: 43,
    text: "Praesent blandit.",
    author: 38,
  },
  {
    id: 44,
    text: "Phasellus in felis. Donec semper sapien a libero.",
    author: 4,
  },
  {
    id: 45,
    text: "Proin eu mi. Nulla ac enim.",
    author: 32,
  },
  {
    id: 46,
    text: "Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.",
    author: 35,
  },
  {
    id: 47,
    text: "Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.",
    author: 31,
  },
  {
    id: 48,
    text: "Morbi vel lectus in quam fringilla rhoncus.",
    author: 1,
  },
  {
    id: 49,
    text: "Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.",
    author: 28,
  },
  {
    id: 50,
    text: "Aenean auctor gravida sem.",
    author: 18,
  },
  {
    id: 51,
    text: "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.",
    author: 23,
  },
  {
    id: 52,
    text: "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",
    author: 10,
  },
  {
    id: 53,
    text: "Nulla facilisi.",
    author: 38,
  },
  {
    id: 54,
    text: "Phasellus id sapien in sapien iaculis congue.",
    author: 15,
  },
  {
    id: 55,
    text: "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.",
    author: 29,
  },
  {
    id: 56,
    text: "Nunc purus. Phasellus in felis.",
    author: 7,
  },
  {
    id: 57,
    text: "Morbi porttitor lorem id ligula.",
    author: 7,
  },
  {
    id: 58,
    text: "Etiam vel augue.",
    author: 34,
  },
  {
    id: 59,
    text: "Proin eu mi.",
    author: 12,
  },
  {
    id: 60,
    text: "Nulla ac enim.",
    author: 1,
  },
  {
    id: 61,
    text: "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.",
    author: 29,
  },
  {
    id: 62,
    text: "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.",
    author: 34,
  },
  {
    id: 63,
    text: "Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    author: 36,
  },
  {
    id: 64,
    text: "Morbi a ipsum. Integer a nibh.",
    author: 11,
  },
  {
    id: 65,
    text: "Duis mattis egestas metus.",
    author: 36,
  },
  {
    id: 66,
    text: "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    author: 39,
  },
  {
    id: 67,
    text: "Pellentesque viverra pede ac diam.",
    author: 32,
  },
  {
    id: 68,
    text: "Pellentesque viverra pede ac diam.",
    author: 14,
  },
  {
    id: 69,
    text: "Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    author: 14,
  },
  {
    id: 70,
    text: "Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.",
    author: 29,
  },
  {
    id: 71,
    text: "Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
    author: 8,
  },
  {
    id: 72,
    text: "Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.",
    author: 36,
  },
  {
    id: 73,
    text: "Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.",
    author: 33,
  },
  {
    id: 74,
    text: "Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.",
    author: 30,
  },
  {
    id: 75,
    text: "In hac habitasse platea dictumst.",
    author: 1,
  },
  {
    id: 76,
    text: "Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    author: 11,
  },
  {
    id: 77,
    text: "Sed accumsan felis.",
    author: 39,
  },
  {
    id: 78,
    text: "Phasellus sit amet erat. Nulla tempus.",
    author: 25,
  },
  {
    id: 79,
    text: "Proin risus.",
    author: 35,
  },
  {
    id: 80,
    text: "Praesent blandit.",
    author: 12,
  },
  {
    id: 81,
    text: "Aliquam non mauris.",
    author: 35,
  },
  {
    id: 82,
    text: "Morbi vel lectus in quam fringilla rhoncus.",
    author: 20,
  },
  {
    id: 83,
    text: "Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.",
    author: 13,
  },
  {
    id: 84,
    text: "Suspendisse potenti.",
    author: 23,
  },
  {
    id: 85,
    text: "Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.",
    author: 2,
  },
  {
    id: 86,
    text: "Aenean sit amet justo.",
    author: 33,
  },
  {
    id: 87,
    text: "Etiam vel augue. Vestibulum rutrum rutrum neque.",
    author: 4,
  },
  {
    id: 88,
    text: "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.",
    author: 17,
  },
  {
    id: 89,
    text: "Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    author: 27,
  },
  {
    id: 90,
    text: "Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.",
    author: 39,
  },
  {
    id: 91,
    text: "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.",
    author: 36,
  },
  {
    id: 92,
    text: "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.",
    author: 23,
  },
  {
    id: 93,
    text: "Proin at turpis a pede posuere nonummy.",
    author: 37,
  },
  {
    id: 94,
    text: "Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
    author: 26,
  },
  {
    id: 95,
    text: "Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.",
    author: 10,
  },
  {
    id: 96,
    text: "Vivamus vel nulla eget eros elementum pellentesque.",
    author: 15,
  },
  {
    id: 97,
    text: "Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.",
    author: 20,
  },
  {
    id: 98,
    text: "Morbi a ipsum.",
    author: 30,
  },
  {
    id: 99,
    text: "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.",
    author: 39,
  },
  {
    id: 100,
    text: "Proin eu mi.",
    author: 24,
  },
];

const comments: PostComment[] = [
  {
    id: 1,
    text: "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.",
    author: 3,
    post: 7,
  },
  {
    id: 2,
    text: "In quis justo.",
    author: 33,
    post: 46,
  },
  {
    id: 3,
    text: "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    author: 19,
    post: 70,
  },
  {
    id: 4,
    text: "Etiam pretium iaculis justo.",
    author: 38,
    post: 82,
  },
  {
    id: 5,
    text: "Morbi a ipsum.",
    author: 13,
    post: 74,
  },
  {
    id: 6,
    text: "In blandit ultrices enim.",
    author: 37,
    post: 82,
  },
  {
    id: 7,
    text: "Quisque id justo sit amet sapien dignissim vestibulum.",
    author: 17,
    post: 49,
  },
  {
    id: 8,
    text: "Proin at turpis a pede posuere nonummy.",
    author: 11,
    post: 37,
  },
  {
    id: 9,
    text: "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    author: 18,
    post: 67,
  },
  {
    id: 10,
    text: "Curabitur in libero ut massa volutpat convallis.",
    author: 25,
    post: 98,
  },
  {
    id: 11,
    text: "In quis justo.",
    author: 28,
    post: 38,
  },
  {
    id: 12,
    text: "Integer tincidunt ante vel ipsum.",
    author: 36,
    post: 65,
  },
  {
    id: 13,
    text: "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    author: 38,
    post: 20,
  },
  {
    id: 14,
    text: "Nulla ac enim.",
    author: 9,
    post: 59,
  },
  {
    id: 15,
    text: "Donec dapibus.",
    author: 8,
    post: 92,
  },
  {
    id: 16,
    text: "Aenean fermentum.",
    author: 27,
    post: 31,
  },
  {
    id: 17,
    text: "Nam tristique tortor eu pede.",
    author: 32,
    post: 27,
  },
  {
    id: 18,
    text: "Sed ante.",
    author: 1,
    post: 42,
  },
  {
    id: 19,
    text: "Aliquam erat volutpat.",
    author: 30,
    post: 17,
  },
  {
    id: 20,
    text: "Aliquam quis turpis eget elit sodales scelerisque.",
    author: 11,
    post: 96,
  },
  {
    id: 21,
    text: "Duis mattis egestas metus.",
    author: 16,
    post: 59,
  },
  {
    id: 22,
    text: "Nam dui.",
    author: 11,
    post: 58,
  },
  {
    id: 23,
    text: "Proin at turpis a pede posuere nonummy.",
    author: 40,
    post: 64,
  },
  {
    id: 24,
    text: "Pellentesque at nulla.",
    author: 21,
    post: 82,
  },
  {
    id: 25,
    text: "Nunc nisl.",
    author: 5,
    post: 30,
  },
  {
    id: 26,
    text: "Proin interdum mauris non ligula pellentesque ultrices.",
    author: 36,
    post: 3,
  },
  {
    id: 27,
    text: "Nulla suscipit ligula in lacus.",
    author: 38,
    post: 26,
  },
  {
    id: 28,
    text: "In congue.",
    author: 2,
    post: 96,
  },
  {
    id: 29,
    text: "Nunc nisl.",
    author: 24,
    post: 4,
  },
  {
    id: 30,
    text: "In sagittis dui vel nisl.",
    author: 11,
    post: 14,
  },
  {
    id: 31,
    text: "Duis bibendum.",
    author: 8,
    post: 71,
  },
  {
    id: 32,
    text: "Nulla nisl.",
    author: 15,
    post: 20,
  },
  {
    id: 33,
    text: "Nulla facilisi.",
    author: 18,
    post: 34,
  },
  {
    id: 34,
    text: "Duis bibendum.",
    author: 25,
    post: 36,
  },
  {
    id: 35,
    text: "Cras non velit nec nisi vulputate nonummy.",
    author: 3,
    post: 2,
  },
  {
    id: 36,
    text: "Mauris sit amet eros.",
    author: 12,
    post: 46,
  },
  {
    id: 37,
    text: "Praesent blandit.",
    author: 26,
    post: 33,
  },
  {
    id: 38,
    text: "Nullam molestie nibh in lectus.",
    author: 16,
    post: 34,
  },
  {
    id: 39,
    text: "Mauris ullamcorper purus sit amet nulla.",
    author: 32,
    post: 88,
  },
  {
    id: 40,
    text: "Nullam porttitor lacus at turpis.",
    author: 4,
    post: 41,
  },
  {
    id: 41,
    text: "Nam dui.",
    author: 28,
    post: 31,
  },
  {
    id: 42,
    text: "Integer ac leo.",
    author: 16,
    post: 47,
  },
  {
    id: 43,
    text: "Ut tellus.",
    author: 10,
    post: 53,
  },
  {
    id: 44,
    text: "Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.",
    author: 17,
    post: 78,
  },
  {
    id: 45,
    text: "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    author: 16,
    post: 98,
  },
  {
    id: 46,
    text: "Sed ante.",
    author: 7,
    post: 44,
  },
  {
    id: 47,
    text: "Morbi porttitor lorem id ligula.",
    author: 36,
    post: 84,
  },
  {
    id: 48,
    text: "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    author: 35,
    post: 5,
  },
  {
    id: 49,
    text: "Nulla tempus.",
    author: 33,
    post: 54,
  },
  {
    id: 50,
    text: "Donec posuere metus vitae ipsum.",
    author: 2,
    post: 58,
  },
  {
    id: 51,
    text: "Donec ut dolor.",
    author: 5,
    post: 45,
  },
  {
    id: 52,
    text: "Etiam justo.",
    author: 39,
    post: 98,
  },
  {
    id: 53,
    text: "Suspendisse potenti.",
    author: 15,
    post: 93,
  },
  {
    id: 54,
    text: "Donec vitae nisi.",
    author: 8,
    post: 27,
  },
  {
    id: 55,
    text: "Morbi quis tortor id nulla ultrices aliquet.",
    author: 34,
    post: 12,
  },
  {
    id: 56,
    text: "Curabitur at ipsum ac tellus semper interdum.",
    author: 23,
    post: 65,
  },
  {
    id: 57,
    text: "Integer a nibh.",
    author: 3,
    post: 83,
  },
  {
    id: 58,
    text: "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    author: 30,
    post: 89,
  },
  {
    id: 59,
    text: "In hac habitasse platea dictumst.",
    author: 26,
    post: 91,
  },
  {
    id: 60,
    text: "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.",
    author: 35,
    post: 17,
  },
  {
    id: 61,
    text: "Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.",
    author: 37,
    post: 56,
  },
  {
    id: 62,
    text: "Vestibulum sed magna at nunc commodo placerat.",
    author: 1,
    post: 68,
  },
  {
    id: 63,
    text: "Aliquam non mauris.",
    author: 26,
    post: 19,
  },
  {
    id: 64,
    text: "Sed ante.",
    author: 33,
    post: 23,
  },
  {
    id: 65,
    text: "Pellentesque eget nunc.",
    author: 14,
    post: 48,
  },
  {
    id: 66,
    text: "Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
    author: 34,
    post: 100,
  },
  {
    id: 67,
    text: "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.",
    author: 9,
    post: 6,
  },
  {
    id: 68,
    text: "Nulla facilisi.",
    author: 15,
    post: 91,
  },
  {
    id: 69,
    text: "Proin risus.",
    author: 8,
    post: 99,
  },
  {
    id: 70,
    text: "Donec semper sapien a libero.",
    author: 19,
    post: 88,
  },
  {
    id: 71,
    text: "Aliquam non mauris.",
    author: 26,
    post: 42,
  },
  {
    id: 72,
    text: "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    author: 17,
    post: 50,
  },
  {
    id: 73,
    text: "Praesent id massa id nisl venenatis lacinia.",
    author: 29,
    post: 59,
  },
  {
    id: 74,
    text: "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.",
    author: 30,
    post: 38,
  },
  {
    id: 75,
    text: "Sed sagittis.",
    author: 27,
    post: 46,
  },
  {
    id: 76,
    text: "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
    author: 25,
    post: 66,
  },
  {
    id: 77,
    text: "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.",
    author: 2,
    post: 85,
  },
  {
    id: 78,
    text: "Sed sagittis.",
    author: 8,
    post: 70,
  },
  {
    id: 79,
    text: "Vestibulum ac est lacinia nisi venenatis tristique.",
    author: 34,
    post: 3,
  },
  {
    id: 80,
    text: "Nullam porttitor lacus at turpis.",
    author: 20,
    post: 39,
  },
  {
    id: 81,
    text: "Nam nulla.",
    author: 38,
    post: 88,
  },
  {
    id: 82,
    text: "Pellentesque eget nunc.",
    author: 24,
    post: 16,
  },
  {
    id: 83,
    text: "Vivamus tortor.",
    author: 32,
    post: 38,
  },
  {
    id: 84,
    text: "Duis ac nibh.",
    author: 3,
    post: 34,
  },
  {
    id: 85,
    text: "Nulla ac enim.",
    author: 26,
    post: 59,
  },
  {
    id: 86,
    text: "Donec ut mauris eget massa tempor convallis.",
    author: 32,
    post: 24,
  },
  {
    id: 87,
    text: "Quisque id justo sit amet sapien dignissim vestibulum.",
    author: 6,
    post: 62,
  },
  {
    id: 88,
    text: "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.",
    author: 33,
    post: 53,
  },
  {
    id: 89,
    text: "Donec quis orci eget orci vehicula condimentum.",
    author: 22,
    post: 24,
  },
  {
    id: 90,
    text: "Suspendisse potenti.",
    author: 23,
    post: 60,
  },
  {
    id: 91,
    text: "Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
    author: 24,
    post: 1,
  },
  {
    id: 92,
    text: "Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.",
    author: 19,
    post: 96,
  },
  {
    id: 93,
    text: "Suspendisse ornare consequat lectus.",
    author: 37,
    post: 50,
  },
  {
    id: 94,
    text: "Proin risus.",
    author: 36,
    post: 10,
  },
  {
    id: 95,
    text: "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.",
    author: 25,
    post: 47,
  },
  {
    id: 96,
    text: "Nunc rhoncus dui vel sem.",
    author: 22,
    post: 38,
  },
  {
    id: 97,
    text: "Nam dui.",
    author: 11,
    post: 95,
  },
  {
    id: 98,
    text: "Nullam molestie nibh in lectus.",
    author: 18,
    post: 78,
  },
  {
    id: 99,
    text: "Nam tristique tortor eu pede.",
    author: 13,
    post: 34,
  },
  {
    id: 100,
    text: "Integer a nibh.",
    author: 27,
    post: 68,
  },
];

const reactions: Reaction[] = [
  { id: 1, type: "DISLIKE", user: 17, post: 92 },
  { id: 2, type: "DISLIKE", user: 12, post: 28 },
  { id: 3, type: "DISLIKE", user: 13, post: 23 },
  { id: 4, type: "DISLIKE", user: 34, post: 65 },
  { id: 5, type: "DISLIKE", user: 20, post: 17 },
  { id: 6, type: "LIKE", user: 8, post: 97 },
  { id: 7, type: "LIKE", user: 14, post: 58 },
  { id: 8, type: "LIKE", user: 33, post: 51 },
  { id: 9, type: "LIKE", user: 12, post: 20 },
  { id: 10, type: "DISLIKE", user: 39, post: 88 },
  { id: 11, type: "DISLIKE", user: 35, post: 43 },
  { id: 12, type: "DISLIKE", user: 5, post: 34 },
  { id: 13, type: "DISLIKE", user: 34, post: 97 },
  { id: 14, type: "LIKE", user: 32, post: 59 },
  { id: 15, type: "DISLIKE", user: 32, post: 74 },
  { id: 16, type: "LIKE", user: 2, post: 7 },
  { id: 17, type: "LIKE", user: 16, post: 79 },
  { id: 18, type: "DISLIKE", user: 8, post: 72 },
  { id: 19, type: "DISLIKE", user: 36, post: 97 },
  { id: 20, type: "LIKE", user: 32, post: 82 },
  { id: 21, type: "DISLIKE", user: 4, post: 78 },
  { id: 22, type: "LIKE", user: 21, post: 5 },
  { id: 23, type: "DISLIKE", user: 11, post: 11 },
  { id: 24, type: "LIKE", user: 12, post: 90 },
  { id: 25, type: "LIKE", user: 4, post: 73 },
  { id: 26, type: "LIKE", user: 14, post: 58 },
  { id: 27, type: "LIKE", user: 33, post: 40 },
  { id: 28, type: "DISLIKE", user: 30, post: 69 },
  { id: 29, type: "DISLIKE", user: 21, post: 59 },
  { id: 30, type: "LIKE", user: 36, post: 80 },
  { id: 31, type: "DISLIKE", user: 19, post: 19 },
  { id: 32, type: "DISLIKE", user: 14, post: 12 },
  { id: 33, type: "LIKE", user: 36, post: 56 },
  { id: 34, type: "LIKE", user: 2, post: 65 },
  { id: 35, type: "LIKE", user: 9, post: 95 },
  { id: 36, type: "LIKE", user: 28, post: 86 },
  { id: 37, type: "LIKE", user: 21, post: 31 },
  { id: 38, type: "LIKE", user: 39, post: 5 },
  { id: 39, type: "DISLIKE", user: 36, post: 41 },
  { id: 40, type: "DISLIKE", user: 5, post: 79 },
  { id: 41, type: "LIKE", user: 21, post: 19 },
  { id: 42, type: "LIKE", user: 26, post: 77 },
  { id: 43, type: "LIKE", user: 33, post: 82 },
  { id: 44, type: "LIKE", user: 25, post: 6 },
  { id: 45, type: "LIKE", user: 14, post: 53 },
  { id: 46, type: "DISLIKE", user: 26, post: 93 },
  { id: 47, type: "DISLIKE", user: 37, post: 70 },
  { id: 48, type: "DISLIKE", user: 6, post: 53 },
  { id: 49, type: "DISLIKE", user: 27, post: 80 },
  { id: 50, type: "DISLIKE", user: 40, post: 23 },
  { id: 51, type: "LIKE", user: 30, post: 68 },
  { id: 52, type: "DISLIKE", user: 24, post: 49 },
  { id: 53, type: "DISLIKE", user: 31, post: 11 },
  { id: 54, type: "DISLIKE", user: 1, post: 7 },
  { id: 55, type: "DISLIKE", user: 10, post: 100 },
  { id: 56, type: "LIKE", user: 22, post: 77 },
  { id: 57, type: "LIKE", user: 5, post: 36 },
  { id: 58, type: "DISLIKE", user: 1, post: 51 },
  { id: 59, type: "LIKE", user: 12, post: 16 },
  { id: 60, type: "LIKE", user: 37, post: 26 },
  { id: 61, type: "DISLIKE", user: 14, post: 81 },
  { id: 62, type: "LIKE", user: 39, post: 96 },
  { id: 63, type: "DISLIKE", user: 26, post: 9 },
  { id: 64, type: "DISLIKE", user: 8, post: 63 },
  { id: 65, type: "DISLIKE", user: 30, post: 74 },
  { id: 66, type: "LIKE", user: 36, post: 2 },
  { id: 67, type: "DISLIKE", user: 15, post: 12 },
  { id: 68, type: "DISLIKE", user: 36, post: 73 },
  { id: 69, type: "DISLIKE", user: 26, post: 60 },
  { id: 70, type: "DISLIKE", user: 24, post: 80 },
  { id: 71, type: "DISLIKE", user: 39, post: 61 },
  { id: 72, type: "DISLIKE", user: 30, post: 83 },
  { id: 73, type: "DISLIKE", user: 10, post: 46 },
  { id: 74, type: "DISLIKE", user: 11, post: 62 },
  { id: 75, type: "DISLIKE", user: 11, post: 36 },
  { id: 76, type: "LIKE", user: 33, post: 5 },
  { id: 77, type: "DISLIKE", user: 16, post: 68 },
  { id: 78, type: "DISLIKE", user: 27, post: 47 },
  { id: 79, type: "LIKE", user: 10, post: 15 },
  { id: 80, type: "DISLIKE", user: 9, post: 94 },
  { id: 81, type: "LIKE", user: 27, post: 68 },
  { id: 82, type: "LIKE", user: 20, post: 71 },
  { id: 83, type: "LIKE", user: 27, post: 73 },
  { id: 84, type: "DISLIKE", user: 29, post: 1 },
  { id: 85, type: "LIKE", user: 38, post: 28 },
  { id: 86, type: "LIKE", user: 10, post: 91 },
  { id: 87, type: "DISLIKE", user: 17, post: 4 },
  { id: 88, type: "LIKE", user: 13, post: 57 },
  { id: 89, type: "DISLIKE", user: 33, post: 98 },
  { id: 90, type: "LIKE", user: 15, post: 6 },
  { id: 91, type: "DISLIKE", user: 36, post: 9 },
  { id: 92, type: "DISLIKE", user: 22, post: 59 },
  { id: 93, type: "LIKE", user: 15, post: 99 },
  { id: 94, type: "DISLIKE", user: 9, post: 27 },
  { id: 95, type: "LIKE", user: 16, post: 54 },
  { id: 96, type: "DISLIKE", user: 36, post: 88 },
  { id: 97, type: "LIKE", user: 27, post: 91 },
  { id: 98, type: "DISLIKE", user: 27, post: 92 },
  { id: 99, type: "LIKE", user: 34, post: 82 },
  { id: 100, type: "LIKE", user: 26, post: 89 },
  { id: 101, type: "LIKE", user: 10, post: 93 },
  { id: 102, type: "DISLIKE", user: 25, post: 19 },
  { id: 103, type: "DISLIKE", user: 28, post: 58 },
  { id: 104, type: "LIKE", user: 30, post: 47 },
  { id: 105, type: "DISLIKE", user: 28, post: 87 },
  { id: 106, type: "DISLIKE", user: 20, post: 63 },
  { id: 107, type: "DISLIKE", user: 34, post: 11 },
  { id: 108, type: "DISLIKE", user: 25, post: 23 },
  { id: 109, type: "LIKE", user: 12, post: 62 },
  { id: 110, type: "DISLIKE", user: 8, post: 60 },
  { id: 111, type: "DISLIKE", user: 11, post: 52 },
  { id: 112, type: "LIKE", user: 34, post: 67 },
  { id: 113, type: "LIKE", user: 28, post: 67 },
  { id: 114, type: "LIKE", user: 26, post: 36 },
  { id: 115, type: "DISLIKE", user: 17, post: 7 },
  { id: 116, type: "DISLIKE", user: 16, post: 53 },
  { id: 117, type: "LIKE", user: 33, post: 58 },
  { id: 118, type: "DISLIKE", user: 38, post: 70 },
  { id: 119, type: "LIKE", user: 17, post: 13 },
  { id: 120, type: "LIKE", user: 5, post: 26 },
  { id: 121, type: "DISLIKE", user: 32, post: 17 },
  { id: 122, type: "DISLIKE", user: 4, post: 52 },
  { id: 123, type: "LIKE", user: 35, post: 71 },
  { id: 124, type: "DISLIKE", user: 13, post: 3 },
  { id: 125, type: "DISLIKE", user: 6, post: 93 },
  { id: 126, type: "LIKE", user: 20, post: 39 },
  { id: 127, type: "DISLIKE", user: 34, post: 39 },
  { id: 128, type: "LIKE", user: 24, post: 32 },
  { id: 129, type: "LIKE", user: 15, post: 30 },
  { id: 130, type: "LIKE", user: 5, post: 87 },
  { id: 131, type: "DISLIKE", user: 19, post: 39 },
  { id: 132, type: "DISLIKE", user: 37, post: 97 },
  { id: 133, type: "DISLIKE", user: 35, post: 83 },
  { id: 134, type: "LIKE", user: 26, post: 6 },
  { id: 135, type: "LIKE", user: 2, post: 80 },
  { id: 136, type: "DISLIKE", user: 7, post: 67 },
  { id: 137, type: "DISLIKE", user: 12, post: 20 },
  { id: 138, type: "LIKE", user: 6, post: 31 },
  { id: 139, type: "LIKE", user: 7, post: 7 },
  { id: 140, type: "LIKE", user: 4, post: 30 },
  { id: 141, type: "LIKE", user: 31, post: 52 },
  { id: 142, type: "DISLIKE", user: 32, post: 40 },
  { id: 143, type: "LIKE", user: 33, post: 80 },
  { id: 144, type: "LIKE", user: 22, post: 46 },
  { id: 145, type: "LIKE", user: 31, post: 89 },
  { id: 146, type: "LIKE", user: 40, post: 22 },
  { id: 147, type: "LIKE", user: 14, post: 57 },
  { id: 148, type: "LIKE", user: 40, post: 36 },
  { id: 149, type: "DISLIKE", user: 28, post: 34 },
  { id: 150, type: "DISLIKE", user: 2, post: 35 },
  { id: 151, type: "LIKE", user: 32, post: 72 },
  { id: 152, type: "DISLIKE", user: 19, post: 48 },
  { id: 153, type: "LIKE", user: 25, post: 18 },
  { id: 154, type: "LIKE", user: 32, post: 87 },
  { id: 155, type: "DISLIKE", user: 31, post: 40 },
  { id: 156, type: "DISLIKE", user: 33, post: 90 },
  { id: 157, type: "DISLIKE", user: 20, post: 63 },
  { id: 158, type: "DISLIKE", user: 34, post: 54 },
  { id: 159, type: "LIKE", user: 19, post: 40 },
  { id: 160, type: "DISLIKE", user: 9, post: 57 },
  { id: 161, type: "DISLIKE", user: 26, post: 37 },
  { id: 162, type: "DISLIKE", user: 21, post: 79 },
  { id: 163, type: "DISLIKE", user: 25, post: 86 },
  { id: 164, type: "LIKE", user: 28, post: 1 },
  { id: 165, type: "DISLIKE", user: 24, post: 98 },
  { id: 166, type: "LIKE", user: 20, post: 4 },
  { id: 167, type: "LIKE", user: 38, post: 46 },
  { id: 168, type: "DISLIKE", user: 39, post: 78 },
  { id: 169, type: "LIKE", user: 9, post: 46 },
  { id: 170, type: "DISLIKE", user: 37, post: 65 },
  { id: 171, type: "LIKE", user: 31, post: 21 },
  { id: 172, type: "LIKE", user: 36, post: 12 },
  { id: 173, type: "LIKE", user: 26, post: 91 },
  { id: 174, type: "LIKE", user: 32, post: 87 },
  { id: 175, type: "LIKE", user: 4, post: 98 },
  { id: 176, type: "DISLIKE", user: 37, post: 59 },
  { id: 177, type: "DISLIKE", user: 37, post: 3 },
  { id: 178, type: "LIKE", user: 14, post: 61 },
  { id: 179, type: "DISLIKE", user: 12, post: 99 },
  { id: 180, type: "LIKE", user: 17, post: 21 },
  { id: 181, type: "DISLIKE", user: 22, post: 4 },
  { id: 182, type: "LIKE", user: 38, post: 27 },
  { id: 183, type: "DISLIKE", user: 40, post: 5 },
  { id: 184, type: "LIKE", user: 20, post: 35 },
  { id: 185, type: "LIKE", user: 37, post: 61 },
  { id: 186, type: "LIKE", user: 40, post: 78 },
  { id: 187, type: "DISLIKE", user: 34, post: 75 },
  { id: 188, type: "LIKE", user: 24, post: 45 },
  { id: 189, type: "DISLIKE", user: 5, post: 49 },
  { id: 190, type: "LIKE", user: 27, post: 41 },
  { id: 191, type: "DISLIKE", user: 33, post: 81 },
  { id: 192, type: "DISLIKE", user: 13, post: 75 },
  { id: 193, type: "LIKE", user: 6, post: 30 },
  { id: 194, type: "DISLIKE", user: 29, post: 45 },
  { id: 195, type: "LIKE", user: 17, post: 93 },
  { id: 196, type: "DISLIKE", user: 2, post: 67 },
  { id: 197, type: "DISLIKE", user: 35, post: 12 },
  { id: 198, type: "LIKE", user: 19, post: 58 },
  { id: 199, type: "DISLIKE", user: 26, post: 14 },
  { id: 200, type: "LIKE", user: 9, post: 5 },
  { id: 201, type: "LIKE", user: 11, post: 55 },
  { id: 202, type: "DISLIKE", user: 37, post: 85 },
  { id: 203, type: "LIKE", user: 34, post: 45 },
  { id: 204, type: "DISLIKE", user: 14, post: 69 },
  { id: 205, type: "LIKE", user: 30, post: 64 },
  { id: 206, type: "DISLIKE", user: 39, post: 30 },
  { id: 207, type: "LIKE", user: 18, post: 12 },
  { id: 208, type: "DISLIKE", user: 26, post: 31 },
  { id: 209, type: "DISLIKE", user: 1, post: 51 },
  { id: 210, type: "LIKE", user: 26, post: 22 },
  { id: 211, type: "DISLIKE", user: 8, post: 29 },
  { id: 212, type: "DISLIKE", user: 12, post: 99 },
  { id: 213, type: "LIKE", user: 29, post: 89 },
  { id: 214, type: "DISLIKE", user: 39, post: 31 },
  { id: 215, type: "DISLIKE", user: 35, post: 22 },
  { id: 216, type: "LIKE", user: 29, post: 35 },
  { id: 217, type: "DISLIKE", user: 25, post: 46 },
  { id: 218, type: "DISLIKE", user: 28, post: 46 },
  { id: 219, type: "LIKE", user: 23, post: 70 },
  { id: 220, type: "DISLIKE", user: 29, post: 67 },
  { id: 221, type: "DISLIKE", user: 11, post: 25 },
  { id: 222, type: "LIKE", user: 29, post: 84 },
  { id: 223, type: "LIKE", user: 7, post: 88 },
  { id: 224, type: "LIKE", user: 33, post: 1 },
  { id: 225, type: "DISLIKE", user: 1, post: 76 },
  { id: 226, type: "LIKE", user: 11, post: 100 },
  { id: 227, type: "LIKE", user: 34, post: 26 },
  { id: 228, type: "LIKE", user: 6, post: 34 },
  { id: 229, type: "LIKE", user: 10, post: 46 },
  { id: 230, type: "DISLIKE", user: 7, post: 69 },
  { id: 231, type: "LIKE", user: 25, post: 33 },
  { id: 232, type: "DISLIKE", user: 39, post: 48 },
  { id: 233, type: "DISLIKE", user: 10, post: 7 },
  { id: 234, type: "DISLIKE", user: 5, post: 49 },
  { id: 235, type: "DISLIKE", user: 22, post: 61 },
  { id: 236, type: "LIKE", user: 8, post: 38 },
  { id: 237, type: "DISLIKE", user: 36, post: 18 },
  { id: 238, type: "DISLIKE", user: 32, post: 24 },
  { id: 239, type: "LIKE", user: 29, post: 43 },
  { id: 240, type: "DISLIKE", user: 27, post: 76 },
  { id: 241, type: "LIKE", user: 40, post: 55 },
  { id: 242, type: "DISLIKE", user: 33, post: 99 },
  { id: 243, type: "DISLIKE", user: 17, post: 58 },
  { id: 244, type: "LIKE", user: 16, post: 47 },
  { id: 245, type: "DISLIKE", user: 35, post: 74 },
  { id: 246, type: "LIKE", user: 18, post: 12 },
  { id: 247, type: "LIKE", user: 22, post: 92 },
  { id: 248, type: "DISLIKE", user: 8, post: 82 },
  { id: 249, type: "LIKE", user: 20, post: 82 },
  { id: 250, type: "DISLIKE", user: 6, post: 30 },
  { id: 251, type: "LIKE", user: 22, post: 12 },
  { id: 252, type: "DISLIKE", user: 19, post: 6 },
  { id: 253, type: "DISLIKE", user: 35, post: 28 },
  { id: 254, type: "DISLIKE", user: 40, post: 28 },
  { id: 255, type: "LIKE", user: 20, post: 23 },
  { id: 256, type: "LIKE", user: 32, post: 31 },
  { id: 257, type: "LIKE", user: 34, post: 39 },
  { id: 258, type: "LIKE", user: 14, post: 5 },
  { id: 259, type: "DISLIKE", user: 16, post: 16 },
  { id: 260, type: "DISLIKE", user: 26, post: 90 },
  { id: 261, type: "DISLIKE", user: 20, post: 100 },
  { id: 262, type: "DISLIKE", user: 20, post: 41 },
  { id: 263, type: "LIKE", user: 34, post: 74 },
  { id: 264, type: "LIKE", user: 34, post: 39 },
  { id: 265, type: "DISLIKE", user: 19, post: 36 },
  { id: 266, type: "DISLIKE", user: 36, post: 59 },
  { id: 267, type: "LIKE", user: 20, post: 35 },
  { id: 268, type: "LIKE", user: 17, post: 8 },
  { id: 269, type: "DISLIKE", user: 17, post: 15 },
  { id: 270, type: "DISLIKE", user: 40, post: 77 },
  { id: 271, type: "LIKE", user: 36, post: 93 },
  { id: 272, type: "LIKE", user: 32, post: 38 },
  { id: 273, type: "DISLIKE", user: 10, post: 12 },
  { id: 274, type: "DISLIKE", user: 30, post: 64 },
  { id: 275, type: "LIKE", user: 4, post: 55 },
  { id: 276, type: "DISLIKE", user: 16, post: 96 },
  { id: 277, type: "DISLIKE", user: 34, post: 76 },
  { id: 278, type: "DISLIKE", user: 2, post: 16 },
  { id: 279, type: "DISLIKE", user: 4, post: 78 },
  { id: 280, type: "LIKE", user: 10, post: 93 },
  { id: 281, type: "DISLIKE", user: 3, post: 100 },
  { id: 282, type: "LIKE", user: 9, post: 100 },
  { id: 283, type: "DISLIKE", user: 2, post: 78 },
  { id: 284, type: "DISLIKE", user: 10, post: 31 },
  { id: 285, type: "DISLIKE", user: 35, post: 59 },
  { id: 286, type: "LIKE", user: 7, post: 36 },
  { id: 287, type: "DISLIKE", user: 24, post: 78 },
  { id: 288, type: "LIKE", user: 31, post: 88 },
  { id: 289, type: "DISLIKE", user: 40, post: 86 },
  { id: 290, type: "LIKE", user: 5, post: 46 },
  { id: 291, type: "LIKE", user: 27, post: 69 },
  { id: 292, type: "LIKE", user: 9, post: 29 },
  { id: 293, type: "LIKE", user: 33, post: 49 },
  { id: 294, type: "DISLIKE", user: 13, post: 29 },
  { id: 295, type: "DISLIKE", user: 34, post: 12 },
  { id: 296, type: "DISLIKE", user: 28, post: 36 },
  { id: 297, type: "LIKE", user: 21, post: 33 },
  { id: 298, type: "DISLIKE", user: 20, post: 58 },
  { id: 299, type: "LIKE", user: 40, post: 49 },
  { id: 300, type: "LIKE", user: 13, post: 36 },
];

interface User {
  id: number;
  name: string;
  age: number;
}

interface Post {
  id: number;
  text: string;
  author: number;
}

interface PostComment {
  id: number;
  text: string;
  author: number;
  post: number;
}

type ReactionType = "LIKE" | "DISLIKE";

interface Reaction {
  id: number;
  type: ReactionType;
  user: number;
  post: number;
}

interface Db {
  users: User[];
  posts: Post[];
  comments: PostComment[];
  reactions: Reaction[];
}

const db: Db = {
  users,
  posts,
  comments,
  reactions,
};
